//Frame Data Types
export const CHARDATA_FETCHING = 'CHARDATA_FETCHING';
export const CHARDATA_FETCH_SUCCESS = 'CHARDATA_FETCH_SUCCESS';
export const CHARDATA_FETCH_ERROR = 'CHARDATA_FETCH_ERROR';

//Category Filter
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const UPDATE_VISIBILITY_FILTER = 'UPDATE_VISIBILITY_FILTER';

//Search Filter
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
