//Frame Data Types
export const CHARDATA_FETCHING = 'CHARDATA_FETCHING';
export const CHARDATA_FETCH_SUCCESS = 'CHARDATA_FETCH_SUCCESS';
export const CHARDATA_FETCH_ERROR = 'CHARDATA_FETCH_ERROR';

//Filter
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const UPDATE_VISBILITY_FILTER = 'UPDATE_VISBILITY_FILTER';
